### ISSUE TITLE
Link doesn't point to the correct place

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity-userdocs#16]
I think the link here called **install Singularity**

<img width="733" alt="screen shot 2018-09-17 at 3 55 57 pm" src="https://user-images.githubusercontent.com/7672924/45646787-5773d280-ba92-11e8-86b4-1900faf37373.png">

Should point [here](https://www.sylabs.io/guides/2.6/user-guide/installation.html), (instead of linking the same section it's already in).

That would probably help with many of the users complaints we've seen recently that the install docs are hard to understand.

**Comment by jmstover** [comment]
I think it's _supposed_ to be pointing at the remote page... but because there's a:
```
------------
Installation
------------
```
header, it's instead linking to that internal link it makes for the header, instead of the _page_ named installation ... 

@devprincess ... For this, what if we changed the Header to be named:  `Quick Installation Steps` instead of `Installation`? I think that link should point to the correct `installation` page then.

**Comment by GodloveD** [comment]
That change would also be useful because it would be a hint to the user that there is more complete installation documentation elsewhere.

**Comment by jchavezlavalle** [comment]
Got it, checking this right now thank you :+1: @GodloveD @jmstover

**Comment by arshadkazmi42** [comment]
Is this issue open? I can work on it.

**Comment by jchavezlavalle** [comment]
Hey @arshadkazmi42 this issue has been fixed, thanks anyway!
