### ISSUE TITLE
Unnecessary to install `dep`, in installation page

### ISSUE THREAD

**Issue by WestleyK** [apptainer/singularity-userdocs#38]
We don't need `dep` to install Singularity.
That step is unnecessary, and can be removed.

**Comment by GodloveD** [comment]
Can you try to install from the 3.0.0 tag and let me know if it is unnecessary to install `dep`?  afaik, you will need to install dep to install that tag. 

Since the 3.0 docs really need to cover the method for installing every version of 3.0.x, I think we need to keep it for now.  Maybe we can remove once we release 3.1.0 and 3.1 docs.

**Comment by WestleyK** [comment]
What!? Your right!!

You do need `dep` if you download singularity 3.0 from the release page...

But, if you clone the latest version, then `./mconfig -V 3.0.0` you don't need `dep` to install...

**Comment by WestleyK** [comment]
Maybe we should add:

```
If your installing < v3.0.1, you will need `dep`, to install dep...
```

**Comment by GodloveD** [comment]
It already says pretty much the same thing right?
```
If you are installing Singularity v3.0.0 you will also need to install dep for dependency resolution.

```

**Comment by WestleyK** [comment]
DUH! can't believe I missed that!

*I wonder what else I missed?* 

Well then, I think we can close this issue.
